#!/bin/sh
set -e
if [ -d /run/systemd/system ]; then
	systemctl daemon-reload || true
fi
if [ "$1" = purge ]; then
	rm -rf /var/lib/nettools
	if getent passwd nettools >/dev/null 2>&1; then
		deluser --system nettools >/dev/null 2>&1 || true
	fi
	if getent group nettools >/dev/null 2>&1; then
		delgroup --system nettools >/dev/null 2>&1 || true
	fi
fi
exit 0
